input.onButtonPressed(Button.A, function () {
    basic.showString("Tq bye!")
})
input.onGesture(Gesture.Shake, function () {
    basic.showString("Hello today i wan to sing sultan tamil song")
})
basic.showNumber(10)
basic.pause(500)
basic.showNumber(9)
basic.pause(500)
basic.showNumber(8)
basic.pause(500)
basic.showNumber(7)
basic.pause(500)
basic.showNumber(6)
basic.pause(500)
basic.showNumber(5)
basic.pause(500)
basic.showNumber(4)
basic.pause(500)
basic.showNumber(3)
basic.pause(500)
basic.showNumber(2)
basic.pause(500)
basic.showNumber(1)
